"""Small, dependency-free Python utilities."""

from toolbelt.iterables import (
    batched,
    chunk_by,
    count_by,
    dedupe,
    first,
    flatten,
    group_by,
    interleave,
    nth,
    partition,
    peekable,
    unique_justseen,
    windowed,
)
from toolbelt.mapping import deep_merge, get_path, invert
from toolbelt.text import (
    camel_case,
    common_prefix,
    human_bytes,
    mask,
    ordinal,
    pluralize,
    slugify,
    snake_case,
    strip_ansi,
    truncate,
    word_wrap,
)

__all__ = [
    "batched",
    "camel_case",
    "chunk_by",
    "common_prefix",
    "count_by",
    "dedupe",
    "deep_merge",
    "first",
    "flatten",
    "get_path",
    "group_by",
    "human_bytes",
    "interleave",
    "invert",
    "mask",
    "nth",
    "ordinal",
    "partition",
    "peekable",
    "pluralize",
    "slugify",
    "snake_case",
    "strip_ansi",
    "truncate",
    "unique_justseen",
    "windowed",
    "word_wrap",
]
__version__ = "0.1.0"
